Create Python_Class
#클래스
 - 이런 것을 쓰는 것은 객체 지향 언어 
   : 클래스라는 틀을 이용해 독립적인 객체를 만들어서 호출 하여 사용한다. 
 - 과자 틀 : 클래스
 - 과자 틀에 의해서 만들어진 과자 : 객체 (Object) - 하나의 객체가 변한다고 나머지 객체가 변하지 않는다
   ※ 과자 틀로 만든 과자들 중 하나를 깨물어도 다른 과자는 변하지 않는다. 
 - 클래스 이름 만들때는 반드시 대문자로 (그냥 약속) 

class Calculator:
          pass
a = Calculator()
print(a)

<__main__.Calculator object at 0x02716850>
 - 메인이라는 파일의 calculaotr라는 클래스의 객체다. at ---- 는 메모리 주소 

a.num = 10  객체 안에 num이라는 숫자에 숫자 할당
num = 20 num이라는 변수에 숫자 할당

print(a.num, num) ※a.num과 num은 독립적이다 
print(id(a.num),id(num))   ※id()는 변수의 주소 확인 함수

b = Calculator()
b.num=30

print(a.num,b.num,num) -> 결과물 10 30 20


a = Calculator()
a.add()
print(a) 결과물 error :

TypeError: add() takes 0 positional arguments but 1 was given

클래수 내부에서 함수를 정의할때, 매서드라 부름 - 
a.add() 에서 a. 는 self = 객체 정보를 넘겨줘야하는 과정이 있어야 한다. 매개변수활용
그 매개변수는 self라는 것을 사용한다 

class Calculator:
          def add(self):
                    print("add함수 내부에서 self값", self)
                    return 10

a = Calculator()
print("add함수 호출전 a변수 값",a)
a.add()
print(a)

결과물
add함수 호출전 a변수 값 <__main__.Calculator object at 0x028D6830>
add함수 내부에서 self값 <__main__.Calculator object at 0x028D6830>
<__main__.Calculator object at 0x028D6830>
주소 값이 같다. 

※클래스에 정의된 add함수 호출
Calculator.add()를 보르면 
error 
TypeError: add() missing 1 required positional argument: 'self'

※객체에 복사된 add함수를 호출하면 self값을 자동으로 매개변수에 넘기는데
  클래스에 정의된 add함수를 호출할때는 매개변수를 자동으로 넘기지 않아 지정해줘야 한다. 
 Calculator.add(a)

print(id(Calculator.add),id(a.add))

※클래스안의 add와 a라는 변수내 add가 주소가 각기 다르다. 다른 메모리 공간안에 있다. 


class Calculator:
          def add(self):
                    return self.num + self.num1


a = Calculator() 

이렇게 정의하고 실행하면 error
AttributeError: 'Calculator' object has no attribute 'num'

num과 num1이라는 값을 저장하겠다는 걸 작성하지 않아서 

a = Calculator() 
a.num = 20          #멤버 변수라고 한다. 
a.num1 = 100
print(a.add())

결과물 : 120 

이제 계산기를 정의 

class Calculator:
          def add(self):
                    return self.num + self.num1
          #빼기
          def sub(self):
                    return self.num - self.num1
          #나누기
          def div(self):
                    return self.num / self.num1
          #곱하기
          def mul(self):
                    return self.num * self.num1

※ Tip 함수의 이름만 정의하고, 기능은 아직 생각하지 않았을때 
   pass로 채워 넣고 나중에 return 값 작성 

print(a.add()) 
print(a.sub())
print(a.div())
print(a.mul())

결과물

120
-80
0.2
2000

지금의 문제 변수를 설정하는 코드 2줄을 쳐야한다.
객체에 num, num1변수 값을 설정하는 함수 


class Calculator:
          #객체에 num, num1 변수값을 설정하는 함수
          def set_data(self,_num, _num1):    ※변수가 헷갈리는 경우 변수 앞에 언더바 
                    self.num = _num
                    self.num1 = _num1
          def add(self):
                    return self.num + self.num1
          #빼기
          def sub(self):
                    return self.num - self.num1
          #나누기
          def div(self):
                    return self.num / self.num1
          #곱하기
          def mul(self):
                    return self.num * self.num1

__xxx__ -> 파이썬 개발자가 지정해준 이름 ex) __main__ / __init__ 등
__init__는 반환값을 돌려줄 수 없어 return을 쓰지 않는다. 
정말 조심해야할 것은 언더바 2개를 앞뒤로! 한개가 아닌 2개!!

class Calculator:
          #생성자함수를 제일 먼저 생성하는 게 개발자들간의 약속
          def __init__(self,_num,_num1):
                    #생성자 함수의 self : 새로 만들어진 객체
                    print("생성자 함수 호출",self)
                    self.num = _num
                    self.num1 = _num1
          #객체에 num, num1 변수값을 설정하는 함수
          def set_data(self,_num, _num1):
                    self.num = _num
                    self.num1 = _num1
          def add(self):
                    return self.num + self.num1
          #빼기
          def sub(self):
                    return self.num - self.num1
          #나누기
          def div(self):
                    return self.num / self.num1
          #곱하기
          def mul(self):
                    return self.num * self.num1

a = Calculator()

이렇게 입력하면 error!

TypeError: __init__() missing 2 required positional arguments: '_num' and '_num1'
※ 매개 변수 2개를 요구하는 생성자를 만들어놔서 2개의 변수 값을 넣어줘야한다. 

a = Calculator(20,100)  ※결과값생성자 함수 호출 <__main__.Calculator object at 0x028D77B0>
print("add함수 호출전 a변수 값",a) 
※add함수 호출전 a변수 값 <__main__.Calculator object at 0x028D77B0>

def __init__(self,_num=0,_num1=0): 기본값 설정 해줄때
calculator() ※ 이렇게 호출해도 기본값 0으로 호출 
calculator(_num1=20) or calculator(,20)※ num1에만 20을 넣고 num은 0
calculator(20,100) num1과 num2를 각각 설정해주면서 시작 


#상속 
 - 상속 때문에 객체 지향 언어를?


※Calculator 클래스를 상속받은 Upgrage 클래스 정의
class UpgradeCal(Calculator):
          pass

a = UpgradeCal()
print("생성된 클래스 객체",a)

결과물 
생성자 함수 호출 <__main__.UpgradeCal object at 0x02916850>  ※calculator class에 대한 함수 실행
생성된 클래스 객체 <__main__.UpgradeCal object at 0x02916850>

a = UpgradeCal(20,50)
print(a.add())
print(a.sub())
print(a.div())
print(a.mul())

결과물
70
-30
0.4
1000

#Calculator 클래스를 상속받은 Upgrage 클래스 정의
class UpgradeCal(Calculator):
          #새로운 함수 정의
          def pow(self):
                    return self.num ** self.num1
          #div 함수에서 0으로 나눌 수 없도록 처리
          def div(self):  #기존에 있는 div 함수 기능은 사라지고, 새롭게 덮어씀
                    if self.num1 ==0: #오버라이딩 
                              print("0으로 나눌 수 없음")
                              return #함수 강제 종료 
                    else :
                              return self.num / self.num1

a = UpgradeCal(20,0)
print(a.div())

결과물 
0으로 나눌 수 없음 
None                   #리턴 값 없음 


#Calculator 클래스를 상속받은 Upgrage 클래스 정의
class UpgradeCal(Calculator):
          #새로운 함수 정의
          def pow(self):
                    return self.num ** self.num1
          #div 함수에서 0으로 나눌 수 없도록 처리
          def div(self):  #기존에 있는 div 함수 기능은 사라지고, 새롭게 덮어씀
                    print("UpgradeCal의 div함수")
                    if self.num1 ==0: #오버라이딩 
                              print("0으로 나눌 수 없음")
                              return #함수 강제 종료 
                    return super().div() #super는 상속 받은 함수를 부르는

a = UpgradeCal(20,10)

print(a.div())

UpgradeCal의 div함수
Calculator의 div함수 #super에서 calculator를 불렀기 때문에 
2.0

※상속을 쓰는 이유는 라이브러리 제공하는 것에 대해 수정을 못하도록 막아 놓기 때문에
우리가 그거 수정해서 쓰려면은 상속 /  오버라이딩이 필요하다. 

#클래스 변수 

#Calculator 클래스를 상속받은 Upgrage 클래스 정의
class UpgradeCal(Calculator):
          num3 = 10 #클래스 변수 : 객체 마다 생성되는 것이 아닌 공용
          #새로운 함수 정의
          def pow(self):
                    return self.num ** self.num1
          #div 함수에서 0으로 나눌 수 없도록 처리
          def div(self):  #기존에 있는 div 함수 기능은 사라지고, 새롭게 덮어씀
                    print("UpgradeCal의 div함수")
                    if self.num1 ==0: #오버라이딩 
                              print("0으로 나눌 수 없음")
                              return #함수 강제 종료 
                    return super().div() #super는 상속 받은 함수를 부르는


print(a.num3, UpgradeCal.num3)

결과물  : 10 10

b=UpgradeCal()
UpgradeCal.num3 = 100

print(a.num3, UpgradeCal.num3, b.num3)

결과물 100,100,100  ※class의 num3변수를 바꿨더니 a까지 변경되었다. 

print(id(a.num3),id(UpgradeCal.num3),id(b.num3))

결과물 : 3개다 주소가 같다.